version: '3.7'
services:
  web:
    build: ./InnotterDjango
    ports:
      - 8000:8000
    env_file:
      - ./InnotterDjango/.env
    entrypoint:
      - ./django-entrypoint.sh
    depends_on:
      - db

  db:
    image: postgres:14.4-alpine
    volumes:
      - ./InnotterDjango/data/db:/var/lib/postgresql/data
    env_file:
      - ./InnotterDjango/.env

  celery:
    build: ./InnotterDjango
    env_file:
      - ./InnotterDjango/.env
    entrypoint:
      - ./celery-entrypoint.sh
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
      image: rabbitmq:3-management-alpine
      ports:
        - 5672:5672
        - 15672:15672
