name: CI/CD

on: [push]

jobs:
  test:
    runs-on: [ubuntu-latest]

    steps:
      - name: clone github repository
        uses: actions/checkout@master

      - name: install python3.9
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: install poetry
        run: pip install poetry

      - name: install all project dependencies
        run: cd InnotterDjango && poetry install

      - name: run all tests for innotter-core-app
        run: cd InnotterDjango && poetry run pytest --cov=.

      - name: run linter for innotter-core-app
        run: cd InnotterDjango && poetry run flake8 .


  build:
    runs-on: [ubuntu-latest]

    needs: [test]

    steps:
      - name: clone github repository
        uses: actions/checkout@master

      - name: build docker image of innotter-core-app
        run: cd InnotterDjango && docker build -t web -f Dockerfile .


  deploy:
    runs-on: [ubuntu-latest]

    needs: [build]

    env:
     API_KEY: ${{ secrets.HEROKU_API_KEY }}
     APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    steps:
      - name: push image to heroku
        run: HEROKU_API_KEY=$API_KEY heroku container:push web -a $APP_NAME

      - name: release image to innotter-core-app
        run: HEROKU_API_KEY=$API_KEY heroku container:release web -a $APP_NAME
#------------------------------------------------------------------------------
