name: test_on_push

on: [push]

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          architecture: 'x64'
      - run: pip install poetry
      - run: cd InnotterDjango && poetry install
      - run: cd InnotterDjango && poetry run pytest --cov=.
      # - run: cd InnotterDjango && poetry run flake8 .

  build_and_pub:
    runs-on: [ubuntu-latest]
    needs: [run_tests]
    env:
     LOGIN: ${{ secrets.DOCKER_LOGIN }}
     NAME: ${{ secrets.DOCKER_NAME }}

    steps:
      - run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u $LOGIN --password-stdin
      - uses: actions/checkout@master
      - run: cd InnotterDjango && docker build -t $NAME -f Dockerfile .
      - run: docker push $LOGIN/$NAME
