name: test_on_push

on: [push]

jobs:
  set-up-env:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: install poetry
        run: pip install poetry

      - name: install flake8
        run: pip install flake8

      - name: run tests
        run: poetry run pytest

      - name: run linter
      - run: flake8 .
