name: test_on_push

on: [push]

jobs:
  set-up-env:
    runs-on: [ubuntu-latest]
    steps:
        - uses: actions/checkout@master
        - uses: actions/setup-python@v1
          with:
            python-version: '3.9'
            architecture: 'x64'
  test:
    runs-on: [ubuntu-latest]
    steps:
        run: pip install poetry
        run: poetry install
        run: poetry run pytest

  lint:
    runs-on: [ubuntu-latest]
    steps:
        run: pip install flake8
        run: flake8 .
